// <auto-generated />
namespace AspNetMVCApi_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class initializeDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initializeDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180835371_initializeDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
